all:
	mpicc -o main-sh.x main-sh.c
	mpicc -o main-mpi.x main-mpi.c
	mpicc -o main-ht.x main-ht.c
	mpicc -o main-lammps.x main-lammps.c
clean:
	rm -f main-sh.x main-mpi.x main-ht.x main-lammps.x
	rm -f time_*.txt output_*.txt

